

INSERT INTO Trainer_Class_Type_Rel VALUES (201, 14);
INSERT INTO Trainer_Class_Type_Rel VALUES (203, 8);
INSERT INTO Trainer_Class_Type_Rel VALUES (204, 6);
INSERT INTO Trainer_Class_Type_Rel VALUES (205, 4);
INSERT INTO Trainer_Class_Type_Rel VALUES (206, 7);
INSERT INTO Trainer_Class_Type_Rel VALUES (207, 2);
INSERT INTO Trainer_Class_Type_Rel VALUES (208, 9);
INSERT INTO Trainer_Class_Type_Rel VALUES (209, 5);
INSERT INTO Trainer_Class_Type_Rel VALUES (210, 10);
INSERT INTO Trainer_Class_Type_Rel VALUES (211, 12);
INSERT INTO Trainer_Class_Type_Rel VALUES (212, 3);
INSERT INTO Trainer_Class_Type_Rel VALUES (214, NULL);
INSERT INTO Trainer_Class_Type_Rel VALUES (215, 15);
INSERT INTO Trainer_Class_Type_Rel VALUES (216, 7);
INSERT INTO Trainer_Class_Type_Rel VALUES (217, 12);
INSERT INTO Trainer_Class_Type_Rel VALUES (218, 11);
INSERT INTO Trainer_Class_Type_Rel VALUES (219, 13);
INSERT INTO Trainer_Class_Type_Rel VALUES (220, 4);
INSERT INTO Trainer_Class_Type_Rel VALUES (221, 3);
INSERT INTO Trainer_Class_Type_Rel VALUES (222, 14);
INSERT INTO Trainer_Class_Type_Rel VALUES (223, 6);
INSERT INTO Trainer_Class_Type_Rel VALUES (224, 4);
INSERT INTO Trainer_Class_Type_Rel VALUES (225, 8);
INSERT INTO Trainer_Class_Type_Rel VALUES (226, 3);
INSERT INTO Trainer_Class_Type_Rel VALUES (228, 7);
INSERT INTO Trainer_Class_Type_Rel VALUES (229, 4);
INSERT INTO Trainer_Class_Type_Rel VALUES (230, 2);
INSERT INTO Trainer_Class_Type_Rel VALUES (231, 11);
INSERT INTO Trainer_Class_Type_Rel VALUES (232, 2);


—------------------------------------------------------------------------------------------------


INSERT INTO trainer_class VALUES (201, 'Youngster');
INSERT INTO trainer_class VALUES (202, 'BugCatcher');
INSERT INTO trainer_class VALUES (203, 'Lass');
INSERT INTO trainer_class VALUES (204, 'Sailor');
INSERT INTO trainer_class VALUES (205, 'JrTrainerM');
INSERT INTO trainer_class VALUES (206, 'JrTrainerF');
INSERT INTO trainer_class VALUES (207, 'Pokemaniac');
INSERT INTO trainer_class VALUES (208, 'SuperNerd');
INSERT INTO trainer_class VALUES (209, 'Hiker');
INSERT INTO trainer_class VALUES (210, 'Biker');
INSERT INTO trainer_class VALUES (211, 'Burglar');
INSERT INTO trainer_class VALUES (212, 'Engineer');
INSERT INTO trainer_class VALUES (214, 'Fisher');
INSERT INTO trainer_class VALUES (215, 'Swimmer');
INSERT INTO trainer_class VALUES (216, 'CueBall');
INSERT INTO trainer_class VALUES (217, 'Gambler');
INSERT INTO trainer_class VALUES (218, 'Beauty');
INSERT INTO trainer_class VALUES (219, 'Psychic');
INSERT INTO trainer_class VALUES (220, 'Rocker');
INSERT INTO trainer_class VALUES (221, 'Juggler');
INSERT INTO trainer_class VALUES (222, 'Tamer');
INSERT INTO trainer_class VALUES (223, 'BirdKeeper');
INSERT INTO trainer_class VALUES (224, 'Blackbelt');
INSERT INTO trainer_class VALUES (225, 'Green1');
INSERT INTO trainer_class VALUES (226, 'ProfOak');
INSERT INTO trainer_class VALUES (228, 'Scientist');
INSERT INTO trainer_class VALUES (229, 'Giovanni');
INSERT INTO trainer_class VALUES (230, 'Rocket');
INSERT INTO trainer_class VALUES (231, 'CooltrainerM');
INSERT INTO trainer_class VALUES (232, 'CooltrainerF');
INSERT INTO trainer_class VALUES (233, 'Bruno');
INSERT INTO trainer_class VALUES (234, 'Brock');
INSERT INTO trainer_class VALUES (235, 'Misty');
INSERT INTO trainer_class VALUES (236, 'LtSurge');
INSERT INTO trainer_class VALUES (237, 'Erika');
INSERT INTO trainer_class VALUES (238, 'Koga');
INSERT INTO trainer_class VALUES (239, 'Blaine');
INSERT INTO trainer_class VALUES (240, 'Sabrina');
INSERT INTO trainer_class VALUES (241, 'Gentleman');
INSERT INTO trainer_class VALUES (242, 'Green2');
INSERT INTO trainer_class VALUES (243, 'Green3');
INSERT INTO trainer_class VALUES (244, 'Lorelei');
INSERT INTO trainer_class VALUES (245, 'Channeler');
INSERT INTO trainer_class VALUES (246, 'Agatha');
INSERT INTO trainer_class VALUES (247, 'Lance');


—-----------------------------------------------------------------------------------------------


INSERT INTO Type (type_name) VALUES ('Bug');
INSERT INTO Type (type_name) VALUES ('Dragon');
INSERT INTO Type (type_name) VALUES ('Electric');
INSERT INTO Type (type_name) VALUES ('Fighting');
INSERT INTO Type (type_name) VALUES ('Fire');
INSERT INTO Type (type_name) VALUES ('Flying');
INSERT INTO Type (type_name) VALUES ('Ghost');
INSERT INTO Type (type_name) VALUES ('Grass');
INSERT INTO Type (type_name) VALUES ('Ground');
INSERT INTO Type (type_name) VALUES ('Ice');
INSERT INTO Type (type_name) VALUES ('Normal');
INSERT INTO Type (type_name) VALUES ('Poison');
INSERT INTO Type (type_name) VALUES ('Psychic');
INSERT INTO Type (type_name) VALUES ('Rock');
INSERT INTO Type (type_name) VALUES ('Water');


—----------------------------------------------------------------------------------------


CALL populate_pokemon_moves_rel('Bulbasaur','grass','poison');
CALL populate_pokemon_moves_rel('Ivysaur','grass','poison');
CALL populate_pokemon_moves_rel('Venusaur','grass','poison');
CALL populate_pokemon_moves_rel('Charmander','fire',NULL);
CALL populate_pokemon_moves_rel('Charmeleon','fire',NULL);
CALL populate_pokemon_moves_rel('Charizard','fire','flying');
CALL populate_pokemon_moves_rel('Squirtle','water',NULL);
CALL populate_pokemon_moves_rel('Wartortle','water',NULL);
CALL populate_pokemon_moves_rel('Blastoise','water',NULL);
CALL populate_pokemon_moves_rel('Caterpie','bug',NULL);
CALL populate_pokemon_moves_rel('Metapod','bug',NULL);
CALL populate_pokemon_moves_rel('Butterfree','bug','flying');
CALL populate_pokemon_moves_rel('Weedle','bug','poison');
CALL populate_pokemon_moves_rel('Kakuna','bug','poison');
CALL populate_pokemon_moves_rel('Beedrill','bug','poison');
CALL populate_pokemon_moves_rel('Pidgey','normal','flying');
CALL populate_pokemon_moves_rel('Pidgeotto','normal','flying');
CALL populate_pokemon_moves_rel('Pidgeot','normal','flying');
CALL populate_pokemon_moves_rel('Rattata','normal',NULL);
CALL populate_pokemon_moves_rel('Raticate','normal',NULL);
CALL populate_pokemon_moves_rel('Spearow','normal','flying');
CALL populate_pokemon_moves_rel('Fearow','normal','flying');
CALL populate_pokemon_moves_rel('Ekans','poison',NULL);
CALL populate_pokemon_moves_rel('Arbok','poison',NULL);
CALL populate_pokemon_moves_rel('Pikachu','electric',NULL);
CALL populate_pokemon_moves_rel('Raichu','electric',NULL);
CALL populate_pokemon_moves_rel('Sandshrew','ground',NULL);
CALL populate_pokemon_moves_rel('Sandslash','ground',NULL);
CALL populate_pokemon_moves_rel('Nidoran(F)','poison',NULL);
CALL populate_pokemon_moves_rel('Nidorina','poison',NULL);
CALL populate_pokemon_moves_rel('Nidoqueen','poison','ground');
CALL populate_pokemon_moves_rel('Nidoran(M)','poison',NULL);
CALL populate_pokemon_moves_rel('Nidorino','poison',NULL);
CALL populate_pokemon_moves_rel('Nidoking','poison','ground');
CALL populate_pokemon_moves_rel('Clefairy','normal',NULL);
CALL populate_pokemon_moves_rel('Clefable','normal',NULL);
CALL populate_pokemon_moves_rel('Vulpix','fire',NULL);
CALL populate_pokemon_moves_rel('Ninetales','fire',NULL);
CALL populate_pokemon_moves_rel('Jigglypuff','normal',NULL);
CALL populate_pokemon_moves_rel('Wigglytuff','normal',NULL);
CALL populate_pokemon_moves_rel('Zubat','poison','flying');
CALL populate_pokemon_moves_rel('Golbat','poison','flying');
CALL populate_pokemon_moves_rel('Oddish','grass','poison');
CALL populate_pokemon_moves_rel('Gloom','grass','poison');
CALL populate_pokemon_moves_rel('Vileplume','grass','poison');
CALL populate_pokemon_moves_rel('Paras','bug','grass');
CALL populate_pokemon_moves_rel('Parasect','bug','grass');
CALL populate_pokemon_moves_rel('Venonat','bug','poison');
CALL populate_pokemon_moves_rel('Venomoth','bug','poison');
CALL populate_pokemon_moves_rel('Diglett','ground',NULL);
CALL populate_pokemon_moves_rel('Dugtrio','ground',NULL);
CALL populate_pokemon_moves_rel('Meowth','normal',NULL);
CALL populate_pokemon_moves_rel('Persian','normal',NULL);
CALL populate_pokemon_moves_rel('Psyduck','water',NULL);
CALL populate_pokemon_moves_rel('Golduck','water',NULL);
CALL populate_pokemon_moves_rel('Mankey','fighting',NULL);
CALL populate_pokemon_moves_rel('Primeape','fighting',NULL);
CALL populate_pokemon_moves_rel('Growlithe','fire',NULL);
CALL populate_pokemon_moves_rel('Arcanine','fire',NULL);
CALL populate_pokemon_moves_rel('Poliwag','water',NULL);
CALL populate_pokemon_moves_rel('Poliwhirl','water',NULL);
CALL populate_pokemon_moves_rel('Poliwrath','water','fighting');
CALL populate_pokemon_moves_rel('Abra','psychic',NULL);
CALL populate_pokemon_moves_rel('Kadabra','psychic',NULL);
CALL populate_pokemon_moves_rel('Alakazam','psychic',NULL);
CALL populate_pokemon_moves_rel('Machop','fighting',NULL);
CALL populate_pokemon_moves_rel('Machoke','fighting',NULL);
CALL populate_pokemon_moves_rel('Machamp','fighting',NULL);
CALL populate_pokemon_moves_rel('Bellsprout','grass','poison');
CALL populate_pokemon_moves_rel('Weepinbell','grass','poison');
CALL populate_pokemon_moves_rel('Victreebel','grass','poison');
CALL populate_pokemon_moves_rel('Tentacool','water','poison');
CALL populate_pokemon_moves_rel('Tentacruel','water','poison');
CALL populate_pokemon_moves_rel('Geodude','rock','ground');
CALL populate_pokemon_moves_rel('Graveler','rock','ground');
CALL populate_pokemon_moves_rel('Golem','rock','ground');
CALL populate_pokemon_moves_rel('Ponyta','fire',NULL);
CALL populate_pokemon_moves_rel('Rapidash','fire',NULL);
CALL populate_pokemon_moves_rel('Slowpoke','water','psychic');
CALL populate_pokemon_moves_rel('Slowbro','water','psychic');
CALL populate_pokemon_moves_rel('Magnemite','electric',NULL);
CALL populate_pokemon_moves_rel('Magneton','electric',NULL);
CALL populate_pokemon_moves_rel('Farfetchd','normal','flying');
CALL populate_pokemon_moves_rel('Doduo','normal','flying');
CALL populate_pokemon_moves_rel('Dodrio','normal','flying');
CALL populate_pokemon_moves_rel('Seel','water',NULL);
CALL populate_pokemon_moves_rel('Dewgong','water','ice');
CALL populate_pokemon_moves_rel('Grimer','poison',NULL);
CALL populate_pokemon_moves_rel('Muk','poison',NULL);
CALL populate_pokemon_moves_rel('Shellder','water',NULL);
CALL populate_pokemon_moves_rel('Cloyster','water','ice');
CALL populate_pokemon_moves_rel('Gastly','ghost','poison');
CALL populate_pokemon_moves_rel('Haunter','ghost','poison');
CALL populate_pokemon_moves_rel('Gengar','ghost','poison');
CALL populate_pokemon_moves_rel('Onix','rock','ground');
CALL populate_pokemon_moves_rel('Drowzee','psychic',NULL);
CALL populate_pokemon_moves_rel('Hypno','psychic',NULL);
CALL populate_pokemon_moves_rel('Krabby','water',NULL);
CALL populate_pokemon_moves_rel('Kingler','water',NULL);
CALL populate_pokemon_moves_rel('Voltorb','electric',NULL);
CALL populate_pokemon_moves_rel('Electrode','electric',NULL);
CALL populate_pokemon_moves_rel('Exeggcute','grass','psychic');
CALL populate_pokemon_moves_rel('Exeggutor','grass','psychic');
CALL populate_pokemon_moves_rel('Cubone','ground',NULL);
CALL populate_pokemon_moves_rel('Marowak','ground',NULL);
CALL populate_pokemon_moves_rel('Hitmonlee','fighting',NULL);
CALL populate_pokemon_moves_rel('Hitmonchan','fighting',NULL);
CALL populate_pokemon_moves_rel('Lickitung','normal',NULL);
CALL populate_pokemon_moves_rel('Koffing','poison',NULL);
CALL populate_pokemon_moves_rel('Weezing','poison',NULL);
CALL populate_pokemon_moves_rel('Rhyhorn','ground','rock');
CALL populate_pokemon_moves_rel('Rhydon','ground','rock');
CALL populate_pokemon_moves_rel('Chansey','normal',NULL);
CALL populate_pokemon_moves_rel('Tangela','grass',NULL);
CALL populate_pokemon_moves_rel('Kangaskhan','normal',NULL);
CALL populate_pokemon_moves_rel('Horsea','water',NULL);
CALL populate_pokemon_moves_rel('Seadra','water',NULL);
CALL populate_pokemon_moves_rel('Goldeen','water',NULL);
CALL populate_pokemon_moves_rel('Seaking','water',NULL);
CALL populate_pokemon_moves_rel('Staryu','water',NULL);
CALL populate_pokemon_moves_rel('Starmie','water','psychic');
CALL populate_pokemon_moves_rel('Mr. Mime','psychic',NULL);
CALL populate_pokemon_moves_rel('Scyther','bug','flying');
CALL populate_pokemon_moves_rel('Jynx','ice','psychic');
CALL populate_pokemon_moves_rel('Electabuzz','electric',NULL);
CALL populate_pokemon_moves_rel('Magmar','fire',NULL);
CALL populate_pokemon_moves_rel('Pinsir','bug',NULL);
CALL populate_pokemon_moves_rel('Tauros','normal',NULL);
CALL populate_pokemon_moves_rel('Magikarp','water',NULL);
CALL populate_pokemon_moves_rel('Gyarados','water','flying');
CALL populate_pokemon_moves_rel('Lapras','water','ice');
CALL populate_pokemon_moves_rel('Ditto','normal',NULL);
CALL populate_pokemon_moves_rel('Eevee','normal',NULL);
CALL populate_pokemon_moves_rel('Vaporeon','water',NULL);
CALL populate_pokemon_moves_rel('Jolteon','electric',NULL);
CALL populate_pokemon_moves_rel('Flareon','fire',NULL);
CALL populate_pokemon_moves_rel('Porygon','normal',NULL);
CALL populate_pokemon_moves_rel('Omanyte','rock','water');
CALL populate_pokemon_moves_rel('Omastar','rock','water');
CALL populate_pokemon_moves_rel('Kabuto','rock','water');
CALL populate_pokemon_moves_rel('Kabutops','rock','water');
CALL populate_pokemon_moves_rel('Aerodactyl','rock','flying');
CALL populate_pokemon_moves_rel('Snorlax','normal',NULL);
CALL populate_pokemon_moves_rel('Articuno','ice','flying');
CALL populate_pokemon_moves_rel('Zapdos','electric','flying');
CALL populate_pokemon_moves_rel('Moltres','fire','flying');
CALL populate_pokemon_moves_rel('Dratini','dragon',NULL);
CALL populate_pokemon_moves_rel('Dragonair','dragon',NULL);
CALL populate_pokemon_moves_rel('Dragonite','dragon','flying');
CALL populate_pokemon_moves_rel('Mewtwo','psychic',NULL);
CALL populate_pokemon_moves_rel('Mew','psychic',NULL);


—----------------------------------------------------------------------------------------------------

CALL populate_trainer_pkmntypes('Rocket', 'Psychic');
CALL populate_trainer_pkmntypes('Rocket', 'Poison');
CALL populate_trainer_pkmntypes('Rocket', 'Normal');
CALL populate_trainer_pkmntypes('Rocket', 'Flying');
CALL populate_trainer_pkmntypes('Green3', 'Flying');
CALL populate_trainer_pkmntypes('Green3', 'Fighting');
CALL populate_trainer_pkmntypes('Green2', 'Flying');
CALL populate_trainer_pkmntypes('Green2', 'Fighting');
CALL populate_trainer_pkmntypes('Gentleman', 'Fighting');
CALL populate_trainer_pkmntypes('Gentleman', 'Electric');
CALL populate_trainer_pkmntypes('Gentleman', 'Fire');


—----------------------------------------------------------------------------------------------------


CALL populate_pokemon_evolutions('Bulbasaur','',FALSE);
CALL populate_pokemon_evolutions('Ivysaur','Bulbasaur',FALSE);
CALL populate_pokemon_evolutions('Venusaur','Ivysaur',TRUE);
CALL populate_pokemon_evolutions('Charmander','',FALSE);
CALL populate_pokemon_evolutions('Charmeleon','Charmander',FALSE);
CALL populate_pokemon_evolutions('Charizard','Charmeleon',TRUE);
CALL populate_pokemon_evolutions('Squirtle','',FALSE);
CALL populate_pokemon_evolutions('Wartortle','Squirtle',FALSE);
CALL populate_pokemon_evolutions('Blastoise','Wartortle',TRUE);
CALL populate_pokemon_evolutions('Caterpie','',FALSE);
CALL populate_pokemon_evolutions('Metapod','Caterpie',FALSE);
CALL populate_pokemon_evolutions('Butterfree','Metapod',TRUE);
CALL populate_pokemon_evolutions('Weedle','',FALSE);
CALL populate_pokemon_evolutions('Kakuna','Weedle',FALSE);
CALL populate_pokemon_evolutions('Beedrill','Kakuna',TRUE);
CALL populate_pokemon_evolutions('Pidgey','',FALSE);
CALL populate_pokemon_evolutions('Pidgeotto','Pidgey',FALSE);
CALL populate_pokemon_evolutions('Pidgeot','Pidgeotto',TRUE);
CALL populate_pokemon_evolutions('Rattata','',FALSE);
CALL populate_pokemon_evolutions('Raticate','Rattata',TRUE);
CALL populate_pokemon_evolutions('Spearow','',FALSE);
CALL populate_pokemon_evolutions('Fearow','Spearow',TRUE);
CALL populate_pokemon_evolutions('Ekans','',FALSE);
CALL populate_pokemon_evolutions('Arbok','Ekans',TRUE);
CALL populate_pokemon_evolutions('Pikachu','',FALSE);
CALL populate_pokemon_evolutions('Raichu','Pikachu',TRUE);
CALL populate_pokemon_evolutions('Sandshrew','',FALSE);
CALL populate_pokemon_evolutions('Sandslash','Sandshrew',TRUE);
CALL populate_pokemon_evolutions('Nidoran(F)','',FALSE);
CALL populate_pokemon_evolutions('Nidorina','Nidoran(F)',FALSE);
CALL populate_pokemon_evolutions('Nidoqueen','Nidorina',TRUE);
CALL populate_pokemon_evolutions('Nidoran(M)','',FALSE);
CALL populate_pokemon_evolutions('Nidorino','Nidoran(M)',FALSE);
CALL populate_pokemon_evolutions('Nidoking','Nidorino',TRUE);
CALL populate_pokemon_evolutions('Clefairy','',FALSE);
CALL populate_pokemon_evolutions('Clefable','Clefairy',TRUE);
CALL populate_pokemon_evolutions('Vulpix','',FALSE);
CALL populate_pokemon_evolutions('Ninetales','Vulpix',TRUE);
CALL populate_pokemon_evolutions('Jigglypuff','',FALSE);
CALL populate_pokemon_evolutions('Wigglytuff','Jigglypuff',TRUE);
CALL populate_pokemon_evolutions('Zubat','',FALSE);
CALL populate_pokemon_evolutions('Golbat','Zubat',TRUE);
CALL populate_pokemon_evolutions('Oddish','',FALSE);
CALL populate_pokemon_evolutions('Gloom','Oddish',FALSE);
CALL populate_pokemon_evolutions('Vileplume','Gloom',TRUE);
CALL populate_pokemon_evolutions('Paras','',FALSE);
CALL populate_pokemon_evolutions('Parasect','Paras',TRUE);
CALL populate_pokemon_evolutions('Venonat','',FALSE);
CALL populate_pokemon_evolutions('Venomoth','Venonat',TRUE);
CALL populate_pokemon_evolutions('Diglett','',FALSE);
CALL populate_pokemon_evolutions('Dugtrio','Diglett',TRUE);
CALL populate_pokemon_evolutions('Meowth','',FALSE);
CALL populate_pokemon_evolutions('Persian','Meowth',TRUE);
CALL populate_pokemon_evolutions('Psyduck','',FALSE);
CALL populate_pokemon_evolutions('Golduck','Psyduck',TRUE);
CALL populate_pokemon_evolutions('Mankey','',FALSE);
CALL populate_pokemon_evolutions('Primeape','Mankey',TRUE);
CALL populate_pokemon_evolutions('Growlithe','',FALSE);
CALL populate_pokemon_evolutions('Arcanine','Growlithe',TRUE);
CALL populate_pokemon_evolutions('Poliwag','',FALSE);
CALL populate_pokemon_evolutions('Poliwhirl','Poliwag',FALSE);
CALL populate_pokemon_evolutions('Poliwrath','Poliwhirl',TRUE);
CALL populate_pokemon_evolutions('Abra','',FALSE);
CALL populate_pokemon_evolutions('Kadabra','Abra',FALSE);
CALL populate_pokemon_evolutions('Alakazam','Kadabra',TRUE);
CALL populate_pokemon_evolutions('Machop','',FALSE);
CALL populate_pokemon_evolutions('Machoke','Machop',FALSE);
CALL populate_pokemon_evolutions('Machamp','Machoke',TRUE);
CALL populate_pokemon_evolutions('Bellsprout','',FALSE);
CALL populate_pokemon_evolutions('Weepinbell','Bellsprout',FALSE);
CALL populate_pokemon_evolutions('Victreebel','Weepinbell',TRUE);
CALL populate_pokemon_evolutions('Tentacool','',FALSE);
CALL populate_pokemon_evolutions('Tentacruel','Tentacool',TRUE);
CALL populate_pokemon_evolutions('Geodude','',FALSE);
CALL populate_pokemon_evolutions('Graveler','Geodude',FALSE);
CALL populate_pokemon_evolutions('Golem','Graveler',TRUE);
CALL populate_pokemon_evolutions('Ponyta','',FALSE);
CALL populate_pokemon_evolutions('Rapidash','Ponyta',TRUE);
CALL populate_pokemon_evolutions('Slowpoke','',FALSE);
CALL populate_pokemon_evolutions('Slowbro','Slowpoke',TRUE);
CALL populate_pokemon_evolutions('Magnemite','',FALSE);
CALL populate_pokemon_evolutions('Magneton','Magnemite',TRUE);
CALL populate_pokemon_evolutions('Farfetchd','',TRUE);
CALL populate_pokemon_evolutions('Doduo','',FALSE);
CALL populate_pokemon_evolutions('Dodrio','Doduo',TRUE);
CALL populate_pokemon_evolutions('Seel','',FALSE);
CALL populate_pokemon_evolutions('Dewgong','Seel',TRUE);
CALL populate_pokemon_evolutions('Grimer','',FALSE);
CALL populate_pokemon_evolutions('Muk','Grimer',TRUE);
CALL populate_pokemon_evolutions('Shellder','',FALSE);
CALL populate_pokemon_evolutions('Cloyster','Shellder',TRUE);
CALL populate_pokemon_evolutions('Gastly','',FALSE);
CALL populate_pokemon_evolutions('Haunter','Gastly',FALSE);
CALL populate_pokemon_evolutions('Gengar','Haunter',TRUE);
CALL populate_pokemon_evolutions('Onix','',TRUE);
CALL populate_pokemon_evolutions('Drowzee','',FALSE);
CALL populate_pokemon_evolutions('Hypno','Drowzee',TRUE);
CALL populate_pokemon_evolutions('Krabby','',FALSE);
CALL populate_pokemon_evolutions('Kingler','Krabby',TRUE);
CALL populate_pokemon_evolutions('Voltorb','',FALSE);
CALL populate_pokemon_evolutions('Electrode','Voltorb',TRUE);
CALL populate_pokemon_evolutions('Exeggcute','',FALSE);
CALL populate_pokemon_evolutions('Exeggutor','Exeggcute',TRUE);
CALL populate_pokemon_evolutions('Cubone','',FALSE);
CALL populate_pokemon_evolutions('Marowak','Cubone',TRUE);
CALL populate_pokemon_evolutions('Hitmonlee','',FALSE);
CALL populate_pokemon_evolutions('Hitmonchan','Hitmonlee',TRUE);
CALL populate_pokemon_evolutions('Lickitung','',TRUE);
CALL populate_pokemon_evolutions('Koffing','',FALSE);
CALL populate_pokemon_evolutions('Weezing','Koffing',TRUE);
CALL populate_pokemon_evolutions('Rhyhorn','',FALSE);
CALL populate_pokemon_evolutions('Rhydon','Rhyhorn',TRUE);
CALL populate_pokemon_evolutions('Chansey','',TRUE);
CALL populate_pokemon_evolutions('Tangela','',TRUE);
CALL populate_pokemon_evolutions('Kangaskhan','',TRUE);
CALL populate_pokemon_evolutions('Horsea','',FALSE);
CALL populate_pokemon_evolutions('Seadra','Horsea',TRUE);
CALL populate_pokemon_evolutions('Goldeen','',FALSE);
CALL populate_pokemon_evolutions('Seaking','Goldeen',TRUE);
CALL populate_pokemon_evolutions('Staryu','',FALSE);
CALL populate_pokemon_evolutions('Starmie','Staryu',TRUE);
CALL populate_pokemon_evolutions('MrMime','',TRUE);
CALL populate_pokemon_evolutions('Scyther','',TRUE);
CALL populate_pokemon_evolutions('Jynx','',TRUE);
CALL populate_pokemon_evolutions('Electabuzz','',TRUE);
CALL populate_pokemon_evolutions('Magmar','',TRUE);
CALL populate_pokemon_evolutions('Pinsir','',TRUE);
CALL populate_pokemon_evolutions('Tauros','',TRUE);
CALL populate_pokemon_evolutions('Magikarp','',FALSE);
CALL populate_pokemon_evolutions('Gyarados','Magikarp',TRUE);
CALL populate_pokemon_evolutions('Lapras','',TRUE);
CALL populate_pokemon_evolutions('Ditto','',TRUE);
CALL populate_pokemon_evolutions('Eevee','',FALSE);
CALL populate_pokemon_evolutions('Vaporeon','Eevee',TRUE);
CALL populate_pokemon_evolutions('Jolteon','Eevee',TRUE);
CALL populate_pokemon_evolutions('Flareon','Eevee',TRUE);
CALL populate_pokemon_evolutions('Porygon','',TRUE);
CALL populate_pokemon_evolutions('Omanyte','',FALSE);
CALL populate_pokemon_evolutions('Omastar','Omanyte',TRUE);
CALL populate_pokemon_evolutions('Kabuto','',FALSE);
CALL populate_pokemon_evolutions('Kabutops','Kabuto',TRUE);
CALL populate_pokemon_evolutions('Aerodactyl','',TRUE);
CALL populate_pokemon_evolutions('Snorlax','',TRUE);
CALL populate_pokemon_evolutions('Articuno','',TRUE);
CALL populate_pokemon_evolutions('Zapdos','',TRUE);
CALL populate_pokemon_evolutions('Moltres','',TRUE);
CALL populate_pokemon_evolutions('Dratini','',FALSE);
CALL populate_pokemon_evolutions('Dragonair','Dratini',FALSE);
CALL populate_pokemon_evolutions('Dragonite','Dragonair',TRUE);
CALL populate_pokemon_evolutions('Mewtwo','',TRUE);
CALL populate_pokemon_evolutions('Mew','',TRUE);



—----------------------------------------------------------------------------------------------------


CALL populate_pokemon_location_rel('Caterpie','Route 25');
CALL populate_pokemon_location_rel('Caterpie','Viridian Forest');
CALL populate_pokemon_location_rel('Metapod','Route 24');
CALL populate_pokemon_location_rel('Metapod','Route 25');
CALL populate_pokemon_location_rel('Metapod','Viridian Forest');
CALL populate_pokemon_location_rel('Weedle','Route 25');
CALL populate_pokemon_location_rel('Weedle','Viridian Forest');
CALL populate_pokemon_location_rel('Kakuna','Route 25');
CALL populate_pokemon_location_rel('Kakuna','Viridian Forest');
CALL populate_pokemon_location_rel('Pidgey','Route 1');
CALL populate_pokemon_location_rel('Pidgey','Route 2');
CALL populate_pokemon_location_rel('Pidgey','Route 3');
CALL populate_pokemon_location_rel('Pidgey','Route 4');
CALL populate_pokemon_location_rel('Pidgey','Route 5');
CALL populate_pokemon_location_rel('Pidgey','Route 6');
CALL populate_pokemon_location_rel('Pidgey','Route 7');
CALL populate_pokemon_location_rel('Pidgey','Route 8');
CALL populate_pokemon_location_rel('Pidgey','Route 12');
CALL populate_pokemon_location_rel('Pidgey','Route 13');
CALL populate_pokemon_location_rel('Pidgey','Route 14');
CALL populate_pokemon_location_rel('Pidgey','Route 15');
CALL populate_pokemon_location_rel('Pidgey','Route 21');
CALL populate_pokemon_location_rel('Pidgey','Route 24');
CALL populate_pokemon_location_rel('Pidgey','Route 25');
CALL populate_pokemon_location_rel('Pidgeotto','Route 14');
CALL populate_pokemon_location_rel('Pidgeotto','Route 15');
CALL populate_pokemon_location_rel('Pidgeotto','Route 21');
CALL populate_pokemon_location_rel('Rattata','Route 1');
CALL populate_pokemon_location_rel('Rattata','Route 2');
CALL populate_pokemon_location_rel('Rattata','Route 4');
CALL populate_pokemon_location_rel('Rattata','Route 9');
CALL populate_pokemon_location_rel('Rattata','Route 16');
CALL populate_pokemon_location_rel('Rattata','Route 21');
CALL populate_pokemon_location_rel('Rattata','Route 22');
CALL populate_pokemon_location_rel('Raticate','Route 16');
CALL populate_pokemon_location_rel('Raticate','Route 17');
CALL populate_pokemon_location_rel('Raticate','Route 18');
CALL populate_pokemon_location_rel('Raticate','Route 21');
CALL populate_pokemon_location_rel('Spearow','Route 3');
CALL populate_pokemon_location_rel('Spearow','Route 4');
CALL populate_pokemon_location_rel('Spearow','Route 9');
CALL populate_pokemon_location_rel('Spearow','Route 10');
CALL populate_pokemon_location_rel('Spearow','Route 11');
CALL populate_pokemon_location_rel('Spearow','Route 16');
CALL populate_pokemon_location_rel('Spearow','Route 17');
CALL populate_pokemon_location_rel('Spearow','Route 18');
CALL populate_pokemon_location_rel('Spearow','Route 22');
CALL populate_pokemon_location_rel('Spearow','Route 23');
CALL populate_pokemon_location_rel('Fearow','Route 17');
CALL populate_pokemon_location_rel('Fearow','Route 18');
CALL populate_pokemon_location_rel('Fearow','Route 23');
CALL populate_pokemon_location_rel('Pikachu','Viridian Forest');
CALL populate_pokemon_location_rel('Pikachu','Power Plant');
CALL populate_pokemon_location_rel('Raichu','Cerulean Cave');
CALL populate_pokemon_location_rel('Raichu','Cerulean Cave');
CALL populate_pokemon_location_rel('Raichu','Power Plant');
CALL populate_pokemon_location_rel('Snadshrew','Route 4');
CALL populate_pokemon_location_rel('Snadshrew','Route 8');
CALL populate_pokemon_location_rel('Snadshrew','Route 9');
CALL populate_pokemon_location_rel('Snadshrew','Route 10');
CALL populate_pokemon_location_rel('Snadshrew','Route 11');
CALL populate_pokemon_location_rel('Snadshrew','Route 23');
CALL populate_pokemon_location_rel('Sandslash','Route 23');
CALL populate_pokemon_location_rel('Sandslash','Cerulean Cave');
CALL populate_pokemon_location_rel('Sandslash','Cerulean Cave');
CALL populate_pokemon_location_rel('Nidorina','Safari Zone');
CALL populate_pokemon_location_rel('Nidorino','Safari Zone');
CALL populate_pokemon_location_rel('Clefairy','Mt. Moon');
CALL populate_pokemon_location_rel('Vulpix','Route 7');
CALL populate_pokemon_location_rel('Vulpix','Route 8');
CALL populate_pokemon_location_rel('Vulpix','Pokemon Mansion');
CALL populate_pokemon_location_rel('Jigglypuff','Route 3');
CALL populate_pokemon_location_rel('Wigglytuff','Cerulean Cave');
CALL populate_pokemon_location_rel('Zubat','Mt. Moon');
CALL populate_pokemon_location_rel('Zubat','Rock Tunnel');
CALL populate_pokemon_location_rel('Zubat','Seafoam Islands');
CALL populate_pokemon_location_rel('Zubat','Victory Road');
CALL populate_pokemon_location_rel('Golbat','Cerulean Cave');
CALL populate_pokemon_location_rel('Golbat','Seafoam Islands');
CALL populate_pokemon_location_rel('Golbat','Victory Road');
CALL populate_pokemon_location_rel('Paras','Mt. Moon');
CALL populate_pokemon_location_rel('Paras','Safari Zone');
CALL populate_pokemon_location_rel('Parasect','Cerulean Cave');
CALL populate_pokemon_location_rel('Parasect','Safari Zone');
CALL populate_pokemon_location_rel('Venonat','Route 12');
CALL populate_pokemon_location_rel('Venonat','Route 13');
CALL populate_pokemon_location_rel('Venonat','Route 14');
CALL populate_pokemon_location_rel('Venonat','Route 15');
CALL populate_pokemon_location_rel('Venonat','Safari Zone');
CALL populate_pokemon_location_rel('Venomoth','Cerulean Cave');
CALL populate_pokemon_location_rel('Venomoth','Victory Road');
CALL populate_pokemon_location_rel('Venomoth','Safari Zone');
CALL populate_pokemon_location_rel('Diglett','Diglett's Cave');
CALL populate_pokemon_location_rel('Dugtrio','Diglett's Cave');
CALL populate_pokemon_location_rel('Meowth','Route 5');
CALL populate_pokemon_location_rel('Meowth','Route 6');
CALL populate_pokemon_location_rel('Meowth','Route 7');
CALL populate_pokemon_location_rel('Meowth','Route 8');
CALL populate_pokemon_location_rel('Psyduck','Seafoam Islands');
CALL populate_pokemon_location_rel('Psyduck','Route 24');
CALL populate_pokemon_location_rel('Psyduck','Route 25');
CALL populate_pokemon_location_rel('Psyduck','Cerulean City');
CALL populate_pokemon_location_rel('Psyduck','Safari Zone');
CALL populate_pokemon_location_rel('Golduck','Seafoam Islands');
CALL populate_pokemon_location_rel('Poliwag','Route 6');
CALL populate_pokemon_location_rel('Poliwag','Route 10');
CALL populate_pokemon_location_rel('Poliwag','Route 11');
CALL populate_pokemon_location_rel('Poliwag','Route 12');
CALL populate_pokemon_location_rel('Poliwag','Route 13');
CALL populate_pokemon_location_rel('Poliwag','Route 17');
CALL populate_pokemon_location_rel('Poliwag','Route 18');
CALL populate_pokemon_location_rel('Poliwag','Route 19');
CALL populate_pokemon_location_rel('Poliwag','Route 20');
CALL populate_pokemon_location_rel('Poliwag','Route 21');
CALL populate_pokemon_location_rel('Poliwag','Route 22');
CALL populate_pokemon_location_rel('Poliwag','Route 23');
CALL populate_pokemon_location_rel('Poliwag','Route 24');
CALL populate_pokemon_location_rel('Poliwag','Route 25');
CALL populate_pokemon_location_rel('Poliwag','Pallet Town');
CALL populate_pokemon_location_rel('Poliwhirl','Route 10');
CALL populate_pokemon_location_rel('Poliwhirl','Celadon City');
CALL populate_pokemon_location_rel('Abra','Route 24');
CALL populate_pokemon_location_rel('Abra','Route 25');
CALL populate_pokemon_location_rel('Kadabra','Cerulean Cave');
CALL populate_pokemon_location_rel('Kadabra','Cerulean Cave');
CALL populate_pokemon_location_rel('Machop','Rock Tunnel');
CALL populate_pokemon_location_rel('Machop','Victory Road');
CALL populate_pokemon_location_rel('Machoke','Victory Road');
CALL populate_pokemon_location_rel('Bellsprout','Route 5');
CALL populate_pokemon_location_rel('Bellsprout','Route 6');
CALL populate_pokemon_location_rel('Bellsprout','Route 7');
CALL populate_pokemon_location_rel('Bellsprout','Route 12');
CALL populate_pokemon_location_rel('Bellsprout','Route 13');
CALL populate_pokemon_location_rel('Bellsprout','Route 14');
CALL populate_pokemon_location_rel('Bellsprout','Route 15');
CALL populate_pokemon_location_rel('Bellsprout','Route 24');
CALL populate_pokemon_location_rel('Bellsprout','Route 25');
CALL populate_pokemon_location_rel('Weepinbell','Route 12');
CALL populate_pokemon_location_rel('Weepinbell','Route 13');
CALL populate_pokemon_location_rel('Weepinbell','Route 14');
CALL populate_pokemon_location_rel('Weepinbell','Route 15');
CALL populate_pokemon_location_rel('Tentacool','Route 12');
CALL populate_pokemon_location_rel('Tentacool','Route 13');
CALL populate_pokemon_location_rel('Tentacool','Route 17');
CALL populate_pokemon_location_rel('Tentacool','Pallet Town');
CALL populate_pokemon_location_rel('Tentacool','Viridian City');
CALL populate_pokemon_location_rel('Tentacool','Route 19');
CALL populate_pokemon_location_rel('Tentacool','Route 20');
CALL populate_pokemon_location_rel('Tentacool','Route 21');
CALL populate_pokemon_location_rel('Geodude','Mt. Moon');
CALL populate_pokemon_location_rel('Geodude','Rock Tunnel');
CALL populate_pokemon_location_rel('Geodude','Victory Road');
CALL populate_pokemon_location_rel('Graveler','Victory Road');
CALL populate_pokemon_location_rel('Ponyta','Pokemon Mansion');
CALL populate_pokemon_location_rel('Slowpoke','Route 10');
CALL populate_pokemon_location_rel('Slowpoke','Celadon City');
CALL populate_pokemon_location_rel('Slowpoke','Safari Zone');
CALL populate_pokemon_location_rel('Slowpoke','Seafoam Islands');
CALL populate_pokemon_location_rel('Slowbro','Route 23');
CALL populate_pokemon_location_rel('Slowbro','Cerulean Cave');
CALL populate_pokemon_location_rel('Slowbro','Seafoam Islands');
CALL populate_pokemon_location_rel('Magnemite','Power Plant');
CALL populate_pokemon_location_rel('Magneton','Cerulean Cave');
CALL populate_pokemon_location_rel('Magneton','Power Plant');
CALL populate_pokemon_location_rel('Farfetchd','Vermilion City');
CALL populate_pokemon_location_rel('Doduo','Route 16');
CALL populate_pokemon_location_rel('Doduo','Route 17');
CALL populate_pokemon_location_rel('Doduo','Route 18');
CALL populate_pokemon_location_rel('Doduo','Safari Zone');
CALL populate_pokemon_location_rel('Dodrio','Cerulean Cave');
CALL populate_pokemon_location_rel('Dodrio','Cerulean Cave');
CALL populate_pokemon_location_rel('Seel','Seafoam Islands');
CALL populate_pokemon_location_rel('Dewgong','Seafoam Islands');
CALL populate_pokemon_location_rel('Grimer','Pokemon Mansion');
CALL populate_pokemon_location_rel('Muk','Pokemon Mansion');
CALL populate_pokemon_location_rel('Shellder','Route 6');
CALL populate_pokemon_location_rel('Shellder','Route 11');
CALL populate_pokemon_location_rel('Shellder','Route 19');
CALL populate_pokemon_location_rel('Shellder','Route 20');
CALL populate_pokemon_location_rel('Shellder','Route 21');
CALL populate_pokemon_location_rel('Shellder','Seafoam Islands');
CALL populate_pokemon_location_rel('Shellder','Seafoam Islands');
CALL populate_pokemon_location_rel('Gastly','Pokemon Tower');
CALL populate_pokemon_location_rel('Haunter','Pokemon Tower');
CALL populate_pokemon_location_rel('Onix', 'Rock Tunnel');
CALL populate_pokemon_location_rel('Onix','Victory Road');
CALL populate_pokemon_location_rel('Drowzee','Route 11');
CALL populate_pokemon_location_rel('Hypno','Cerulean Cave');
CALL populate_pokemon_location_rel('Krabby','Route 6');
CALL populate_pokemon_location_rel('Krabby','Route 11');
CALL populate_pokemon_location_rel('Krabby','Route 12');
CALL populate_pokemon_location_rel('Krabby','Route 13');
CALL populate_pokemon_location_rel('Krabby','Route 17');
CALL populate_pokemon_location_rel('Krabby','Route 18');
CALL populate_pokemon_location_rel('Krabby','Route 24');
CALL populate_pokemon_location_rel('Krabby','Route 25');
CALL populate_pokemon_location_rel('Krabby','Cerulean City');
CALL populate_pokemon_location_rel('Krabby','Vermilion City');
CALL populate_pokemon_location_rel('Krabby','Fuchsia City');
CALL populate_pokemon_location_rel('Krabby','Cerulean Cave');
CALL populate_pokemon_location_rel('Krabby','Safari Zone');
CALL populate_pokemon_location_rel('Kingler','Route 23');
CALL populate_pokemon_location_rel('Kingler','Seafoam Islands');
CALL populate_pokemon_location_rel('Voltorb','Route 10');
CALL populate_pokemon_location_rel('Voltorb','Power Plant');
CALL populate_pokemon_location_rel('Electrode','Cerulean Cave');
CALL populate_pokemon_location_rel('Exeggcute','Safari Zone');
CALL populate_pokemon_location_rel('Cubone','Pokemon Tower');
CALL populate_pokemon_location_rel('Marowak','Cerulean Cave');
CALL populate_pokemon_location_rel('Marowak','Victory Road');
CALL populate_pokemon_location_rel('Hitmonlee','Saffron City');
CALL populate_pokemon_location_rel('Hitmonchan','Saffron City');
CALL populate_pokemon_location_rel('Lickitung','Route 18');
CALL populate_pokemon_location_rel('Koffing','Pokemon Mansion');
CALL populate_pokemon_location_rel('Weezing','Pokemon Mansion');
CALL populate_pokemon_location_rel('Rhyhorn','Safari Zone');
CALL populate_pokemon_location_rel('Rhydon','Cerulean Cave');
CALL populate_pokemon_location_rel('Chansey','Cerulean Cave');
CALL populate_pokemon_location_rel('Chansey','Safari Zone');
CALL populate_pokemon_location_rel('Tangela','Route 21');
CALL populate_pokemon_location_rel('Kangaskhan','Safari Zone');
CALL populate_pokemon_location_rel('Horsea','Route 19');
CALL populate_pokemon_location_rel('Horsea','Route 20');
CALL populate_pokemon_location_rel('Horsea','Route 21');
CALL populate_pokemon_location_rel('Horsea','Seafoam Islands');
CALL populate_pokemon_location_rel('Seadra','Route 23');
CALL populate_pokemon_location_rel('Seadra','Cerulean Cave');
CALL populate_pokemon_location_rel('Goldeen','Route 6');
CALL populate_pokemon_location_rel('Goldeen','Route 10');
CALL populate_pokemon_location_rel('Goldeen','Route 11');
CALL populate_pokemon_location_rel('Goldeen','Route 12');
CALL populate_pokemon_location_rel('Goldeen','Route 13');
CALL populate_pokemon_location_rel('Goldeen','Route 17');
CALL populate_pokemon_location_rel('Goldeen','Route 18');
CALL populate_pokemon_location_rel('Goldeen','Route 19');
CALL populate_pokemon_location_rel('Goldeen','Route 20');
CALL populate_pokemon_location_rel('Goldeen','Route 21');
CALL populate_pokemon_location_rel('Goldeen','Route 22');
CALL populate_pokemon_location_rel('Goldeen','Route 23');
CALL populate_pokemon_location_rel('Goldeen','Route 24');
CALL populate_pokemon_location_rel('Goldeen','Route 25');
CALL populate_pokemon_location_rel('Goldeen','Pallet Town');
CALL populate_pokemon_location_rel('Seaking','Route 23');
CALL populate_pokemon_location_rel('Seaking','Fuchsia City');
CALL populate_pokemon_location_rel('Seaking','Cerulean Cave');
CALL populate_pokemon_location_rel('Staryu','Route 19');
CALL populate_pokemon_location_rel('Staryu','Route 20');
CALL populate_pokemon_location_rel('Staryu','Route 21');
CALL populate_pokemon_location_rel('Staryu','Cinnabar Island');
CALL populate_pokemon_location_rel('Staryu','Seafoam Islands');
CALL populate_pokemon_location_rel('Staryu','Viridian City');
CALL populate_pokemon_location_rel('Mr. Mime','Route 2');
CALL populate_pokemon_location_rel('Jynx','Cerulean City');
CALL populate_pokemon_location_rel('Magmar','Pokemon Mansion');
CALL populate_pokemon_location_rel('Pinsir','Safari Zone');
CALL populate_pokemon_location_rel('Tauros','Safari Zone');
CALL populate_pokemon_location_rel('Ditto','Route 13');
CALL populate_pokemon_location_rel('Ditto','Route 14');
CALL populate_pokemon_location_rel('Ditto','Route 15');
CALL populate_pokemon_location_rel('Ditto','Route 23');
CALL populate_pokemon_location_rel('Ditto','Cerulean Cave');
CALL populate_pokemon_location_rel('Eevee','Celadon City');
CALL populate_pokemon_location_rel('Porygon','Celadon City');
CALL populate_pokemon_location_rel('Omanyte','Cinnabar Island');
CALL populate_pokemon_location_rel('Kabuto','Cinnabar Island');
CALL populate_pokemon_location_rel('Aerodactyl','Cinnabar Island');
CALL populate_pokemon_location_rel('Snorlax','Route 12');
CALL populate_pokemon_location_rel('Snorlax','Route 16');
CALL populate_pokemon_location_rel('Articuno','Seafoam Islands');
CALL populate_pokemon_location_rel('Zapdos','Power Plant');
CALL populate_pokemon_location_rel('Moltres','Victory Road');
CALL populate_pokemon_location_rel('Dratini','Safari Zone');
CALL populate_pokemon_location_rel('Mewtwo','Cerulean Cave');


—----------------------------------------------------------------------------------------------------


CALL populate_pokemon_type_rel('Rocket', 'Psychic');
CALL populate_pokemon_type_rel('Rocket', 'Poison');
CALL populate_pokemon_type_rel('Rocket', 'Normal');
CALL populate_pokemon_type_rel('Rocket', 'Flying');
CALL populate_pokemon_type_rel('Green3', 'Flying');
CALL populate_pokemon_type_rel('Green3', 'Fighting');
CALL populate_pokemon_type_rel('Green2', 'Flying');
CALL populate_pokemon_type_rel('Green2', 'Fighting');
CALL populate_pokemon_type_rel('Gentleman', 'Fighting');
CALL populate_pokemon_type_rel('Gentleman', 'Electric');
CALL populate_pokemon_type_rel('Gentleman', 'Fire');








